### ISSUE TITLE
Similar data in parlnet

### ISSUE THREAD

**Issue by briatte** [saschagobel/legislatoR#3]
Dear @saschagobel and @simonmunzert 

I have collected some data similar to yours in https://github.com/briatte/parlnet -- although my data collection process looks much less formalised than yours.

I'm planning to update parlnet in one month or two, so might pop up again here by then.

All the best,

François

**Comment by saschagobel** [comment]
Hi François,

thanks for letting us know, parlnet looks great! We will add it to the list of data projects for which we generate IDs for easy data integration between projects.

Best
Sascha
