### ISSUE TITLE
Data does not load

### ISSUE THREAD

**Issue by CK-hgw-1456** [saschagobel/legislatoR#8]
The "legislatoR::get_XXXX" functions do not work anymore. Several machines and R Versions checked by several people, all continue to get the same error message: "Error in readRDS(connect): unknown input format".  
Still worked like a charm in August - hope this can be solved. What an amazing package.

**Comment by saschagobel** [comment]
Thanks for letting us know, we are looking into it. The legislatoR package collects the CLD tables directly from the corresponding Harvard Dataverse repository via a URL that accesses the API. These URLs still work for a manual download. However, currently, they do not seem to work for downloading via wget/curl from the terminal. Given that this should work, I suspect it is an error on their end. I already contacted the support.

In the meantime, you can download the .rds, .csv, or .sqlite files directly from the Dataverse using the following link: https://dataverse.harvard.edu/dataverse/cld

**Comment by saschagobel** [comment]
Working again. The Dataverse's AWS web application firewall blocked all GET requests from certain areas, apparently requests from Germany or parts of it. Something triggered the assumption that traffic from these areas might be coming from bots invoking a challenge that asks the client to demonstrate that it is a browser.
